#!/usr/bin/env bash

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
	echo "Usage: $0 <file> [namespace=ft]"
	exit 1
fi


source fct.sh
testedNamespace=$([[ -z "$2" ]] && echo "ft" || echo "$2")

try_one () {
	output_file=$(basename "$1" .cpp).out

	compile "$1" "${testedNamespace}" "${output_file}" || return 0

  set -e
  valgrind \
      --exit-on-first-error=yes \
      --error-exitcode=1 \
      --log-file=/dev/null \
      ./${output_file} > /dev/null 2>&1
    # || echo leak at "$1" && exit 1
}

try_one $1
